### ISSUE TITLE
Opening image file in text mode

### ISSUE THREAD

**Issue by shooshx** [EarlGray/ext2py#1]
ext2.py class E2IO does:
self.f = open(source)
on windows, if the file has "/n" they will be read as "/r/n" since the default open mode is text mode
this should be changed to
self.f = open(source, "rb")
I have an image where this prevents the correct reading of the image

Likewise, in method pull(), you need to open(to_file, "wb")

**Comment by EarlGray** [comment]
Thank you for spotting this!
